import Head from "next/head";
import Link from "next/link";
import { Inter } from "@next/font/google";
import Navbar from "../components/Navbar";
import Dashboard from "../components/Dashboard";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <Dashboard/>
        
      </main>
    </>
  );
}
